### ISSUE TITLE
CentOS 5.6 64ビット、setsockopt が Errno::EINVAL

### ISSUE THREAD

**Issue by tora** [suzumura-ss/castoro#25]
peerサーバで以下のようなエラー
peer01 crepd[16632]: Replicating 1.2.3 to peer02:30148 started.
peer01 crepd[16632]: Exception: Errno::EINVAL "Invalid argument" ["/usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.1.0/lib/castoro-peer/extended_tcp_socket.rb:72:in `setsockopt'", "/usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.1.0/lib/castoro-peer/extended_tcp_socket.rb:72:in`set_receive_timed_out'", "/usr/local/lib/ruby/gems/1.9.1/gems/castoro-peer-0.1.0/lib/castoro-peer/crepd_sender.rb:108:in `do_replicate_command'"]

gemは、
castoro-common (0.1.0)
castoro-manipulator (0.1.1)
castoro-peer (0.1.0)

OS: CentOS 5.6 64ビット

**Comment by tora** [comment]
https://github.com/ToshiyukiTerashita/castoro/blob/master/castoro-peer/lib/castoro-peer/extended_tcp_socket.rb

```
  def set_receive_timed_out( timedout )
    t = Time.at( timedout )
    optval = [t.tv_sec, t.tv_usec].pack('ll')
    setsockopt(Socket::SOL_SOCKET, Socket::SO_RCVTIMEO, optval)
  end
```

pack() に与えている 'll' を 'qq' に変更すると、動作した。
    l         | Integer | 32-bit signed integer, native endian (int32_t)
    q         | Integer | 64-bit signed integer, native endian (int64_t)

CentOS 5.6 64ビットOS 上では、'll' ではなく 'qq' とする必要があるようだ。

Socket::SO_RCVTIMEO へは、struct timeval 構造体をデータとして渡す。
struct timeval の CentOS 5.6 上での定義は、メンバー変数として long int 型が二つ。
秒を表す tv_sec と
マイクロ秒を表す tv_usec

この long int 型のサイズが、
32ビットの場合、4バイト
64ビットの場合、8バイト

**Comment by tora** [comment]
castoro-peer-0.1.2  2011-10-04 にて、対処いたしました。
